### ISSUE TITLE
Crash when attempting to start Firefox on it.

### ISSUE THREAD

**Issue by vi** [nwrkbiz/android-xserver#41]
```
FATAL EXCEPTION: Thread-1252
Process: au.com.darkside.xdemo, PID: 24344
java.lang.NullPointerException: Attempt to read from field 'au.com.darkside.xserver.Window au.com.darkside.xserver.Selection._ownerWindow' on a null object reference in method 'void au.com.darkside.xserver.Selection.processConvertSelectionRequest(au.com.darkside.xserver.XServer, au.com.darkside.xserver.Client, int)'
        at au.com.darkside.xserver.Selection.processConvertSelectionRequest(Selection.java:277)
        at au.com.darkside.xserver.Selection.processRequest(Selection.java:140)
        at au.com.darkside.xserver.Client.processRequest(Client.java:387)
        at au.com.darkside.xserver.Client.doComms(Client.java:258)
        at au.com.darkside.xserver.Client.run(Client.java:126)
```

**Comment by utzcoz** [comment]
@vi  I think I have fixed it with https://github.com/nwrkbiz/android-xserver/pull/29 some years ago. You can download the latest source code, build and use it to test again.

**Comment by vi** [comment]
Maybe it's time to upload apk as a 1.32 Github release?

**Comment by utzcoz** [comment]
Maybe it requires @nwrkbiz to do this release.

**Comment by nwrkbiz** [comment]
@utzcoz @vi :
https://github.com/nwrkbiz/android-xserver/releases/tag/1.32
